### ISSUE TITLE
Simple syntax

### ISSUE THREAD

**Issue by vladshcherbin** [jagi/meteor-astronomy-simple-validators#1]
Okay, since this is the simple validators package, maybe we can have a normal human syntax?

``` js
Post.schema.addValidators({
  title: 'and([str,minlen(5),required])'
});
```

Why do we need the **and** word?
It is obvious, ALL the passed rules must be validated. Why do we need OR validator ? I have never seen or used it anywhere, never missed it. Do we need it at all? Don't write a rule you don't want to validate.

Can we have this syntax instead:

``` js
Post.schema.addValidators({
  title: 'required|string|min:5'
});
```

This is a simple validation package, lets make it simple. Let the geeks and nerds use [normal package](https://github.com/jagi/meteor-astronomy-validators) instead if they want such flexibility. Let this package has simplicity and beauty.

@jagi can we have this one please?

**Comment by lukejagodzinski** [comment]
There is the simple validator parser that translate a string from the `simple-validators` into functions from the `validators` package. I wanted to provide almost all features that are possible with standard validators in simple validators.

You can nest validation rules and there are situation when you will need `or` validator.

I don't think that there is need for making it simpler. You just have to add `and([` and `)` to any rule. Moreover `|` between rules suggest that it's `or` not `and`. There is no point of making things as simple as possible. We could make it event simple, why don't just write `title: 'r|s|m:5'` but will it make your life easier no to write few more characters? :)

**Comment by vladshcherbin** [comment]
@jagi yep, I understand, you made all the functionality with a smaller syntax.

I came from php and Laravel, which is the framework, loved for its simplicity and pleasure to use. I like the [validation](http://laravel.com/docs/5.0/validation) there, so the rules styling is from there.

I thought, we could make the validation definition similar to validation there. When you have 1-3 models - it is not a big deal to use **and** - but it is already ugly and not necessary for half of the users. In Lavavel we don't have this weird **or** thing and we are happy without it.

I would make this syntax by myself, but for now I don't have enough JS experience to do such stuff. But if we will stay with current syntax, guess I will try to somehow make it work as in Laravel cuz I absolutely love it and don't want to use this weird and/or one.

@jagi can you tell me, shall I need to start trying? :)

**Comment by lukejagodzinski** [comment]
Let's me just think about that. I don't want to make hasty decisions. Maybe I could create some exception here in the parsing function. But I have to rethink it. I'm adding this issue to `features request` list and I will let you know soon what I've decided :)

**Comment by vladshcherbin** [comment]
@jagi sure, think about it, see some Laravel examples in the docs, they are simple and human-like. If you would like to stick with the current version, I'll understand and will try to do it myself. Let me know, you are the boss ;)

**Comment by lukejagodzinski** [comment]
@VladShcherbin I the next Simple Validator module version I will implement the feature you requested, I mean that it will implicitly treat `"required,str,minlen(5)"` as `"and([required,str,minlen(5)])"`. Stay tuned :)

**Comment by vladshcherbin** [comment]
@jagi great news! thank you ;)

**Comment by lukejagodzinski** [comment]
Ok I've made a fix as I wrote in the other issue :). Please read the wiki page for Validators and Simple Validators :). If you have any question, feel free to ask them on the gitter.
